service: word-cloud

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
  s3BucketName: ${file(env/config.json):s3BucketName}
  profile: ${file(env/config.json):profile}

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-2
  profile: ${self:custom.profile}
  environment:
    bucketName: ${self:custom.s3BucketName}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - ${self:custom.s3BucketName}
            - '/*'

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .git/**
    - env/**
    - dist/**
    - result/**
    - test/**
    - make_word_cloud.py
    - package.json
    - package-lock.json
    - venv/**

functions:
  make:
    handler: handler.handler

resources:
  Resources:
    s3OutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}

